### ISSUE TITLE
about primary key 

### ISSUE THREAD

**Issue by sumincy** [Jamling/Android-ORM#16]
when  use  batchinsert  , the java bean dont need  defined  annotation  "id"  for  a property , but use  insert ,you must. It will check the primary key .   if not defined id ,it throwed a  ORMException. 

in the Session class . cloum 842.

**Comment by Jamling** [comment]
The `batchInsert` will ignore the `Primary Key` column, and the PK check is optional in `insert`,  the concrete exception is not dealt, can you send me the detail ORMException stack? I need it to get real cause.

**Comment by sumincy** [comment]
ok,  the error caused by the  NullPointException   : pk.equals(colName)   when i did not define the annotation "id" .  the pk is empty.

1 cn.ieclipse.aorm.ORMException:java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
--
2 cn.ieclipse.aorm.Session$Row.<init>(Session.java:852)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
6 cn.ieclipse.aorm.Session$Row.<init>(Session.java:842)
7 cn.ieclipse.aorm.Session.insert(Session.java:184)
8 cn.ieclipse.aorm.Session.insert(Session.java:202)
9 com.huateng.merchant.ui.activity.browse.ActivityAboutUs$1$2.onClick(ActivityAboutUs.java:116)
10 android.view.View.performClick(View.java:4909)
11 android.view.View$PerformClick.run(View.java:20390)
12 android.os.Handler.handleCallback(Handler.java:815)
13 android.os.Handler.dispatchMessage(Handler.java:104)
14 android.os.Looper.loop(Looper.java:194)
15 android.app.ActivityThread.main(ActivityThread.java:5860)
16 java.lang.reflect.Method.invoke(Native Method)
17 java.lang.reflect.Method.invoke(Method.java:372)
18 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
19 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by Jamling** [comment]
Thank you for your feedback, I will fix it later
